# Streamlit Configuration for Nimbus Platform Deployment

[theme]
# Premium color scheme matching the app design
primaryColor="#667eea"
backgroundColor="#f5f7fa"
secondaryBackgroundColor="#ffffff"
textColor="#2d3748"
font="sans serif"

[server]
# Server configuration for cloud deployment
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
# Client configuration
showErrorDetails = false
toolbarMode = "minimal"
